#!/bin/sh -e

export XDG_RUNTIME_DIR="/run/user/$(id -u)"

mkdir -p "${XDG_RUNTIME_DIR}/snap.sway"
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_CONFIG_HOME}/sway/"

# FIXME: only regenerate on install or refresh. use hooks
# if [[ ! -e "${GDK_PIXBUF_MODULE_FILE}" ]] ; then
    mkdir -p "$(dirname ${GDK_PIXBUF_MODULE_FILE})"
    ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > "${GDK_PIXBUF_MODULE_FILE}"
# fi

cp -rn ${SNAP}/etc/sway ${XDG_CONFIG_HOME}/

exec "$SNAP/usr/bin/sway" "$@"