name: sway
# title:
type: app
base: core18
version: '1.3.0-2-0classic2'
summary: i3-compatible Wayland compositor
description: |
  Sway is a tiling window manager and Wayland compositor, inspired by i3, and written in C. It is designed as a drop in replacement for i3 using the more modern Wayland display server protocol and wlroots compositor library.
# license:

# icon: sway.png

grade: stable
confinement: classic

environment:
  SHELL: bash
  # LANG: null
  LC_ALL: C
  # LC_ALL: C.UTF-8

  # --- Prep GDK, GTK, Clutter ---
  GDK_BACKEND: wayland
  CLUTTER_BACKEND: wayland
  QT_QPA_PLATFORM: wayland-egl


apps:
  sway:
    command: usr/bin/sway
    # extensions:
    #   - gnome-3-28
    desktop: usr/share/wayland-sessions/sway.desktop
  swaybar:
    command: usr/bin/swaybar
    aliases: [ swaybar ]
  swaybg:
    command: usr/bin/swaybg
    aliases: [ swaybg ]
  swayidle:
    command: usr/bin/swayidle
    aliases: [ swayidle ]
  swaylock:
    command: usr/bin/swaylock
    aliases: [ swaylock ]
  swaymsg:
    command: usr/bin/swaymsg
    aliases: [ swaymsg ]
  swaynag:
    command: usr/bin/swaynag
    aliases: [ swaynag ]


slots:
  x11-slot:
    interface: x11
  wayland-slot:
    interface: wayland


plugs:
  wayland:
  x11:
  desktop:
  desktop-legacy:
  opengl:
  framebuffer:
  hardware-observe:
  display-control:
  locale-control:
  login-session-control:
  login-session-observe:


layout:
  /etc/sway:
    symlink: $SNAP/etc/sway
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11


build-packages:
  - cmake # meson likes cmake
  - ctags # meson
  - pkgconf
  - quilt


parts:
  snapcraft-preload:
    source: https://github.com/sd-hd/snapcraft-preload.git
    source-branch: lib_version
    # source: snapcraft-preload/
    # source-type: local
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    # stage-packages:
    # - lib32gcc1
    # - lib32stdc++6
    # - libc6-i386


  externals:
     plugin: dump
     source: .
     organize:
       sway-config: etc/sway/config


  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.18'
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin


  json-c:
    source: https://github.com/json-c/json-c.git
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]


  sway:
    after: [ json-c, wayland-protocols ] ## TODO: optional after xwayland
    source: https://github.com/swaywm/sway.git
    source-tag: 'v1.3'
    plugin: meson
    meson-version: 0.53.0
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
      #- --buildtype=release
      -  -Dman-pages=disabled
      -  -Dgdk-pixbuf=enabled
      -  -Dtray=disabled ## TODO: needs libsystemd
      -  -Dxwayland=enabled

      - -Dfreerdp=disabled ## TODO: from wlroots
      - -Dwlroots:freerdp=disabled ## TODO: from wlroots

      - -Dlibcap=enabled
      - -Dlogind=enabled
      - -Dlogind-provider=systemd

      - -Dexamples=false
    override-pull: |
      set -eux
      snapcraftctl pull      
      git clone -b 0.9.1 https://github.com/swaywm/wlroots.git subprojects/wlroots
    build-packages:
      - libcairo2-dev
      - libdbus-1-dev
      - libevdev-dev
      - libdrm-dev
      - libpango1.0-dev
      - libjson-c-dev
      - libgdk-pixbuf2.0-dev
      - libsystemd-dev
      - libcap-dev
      - libgbm-dev
      - libinput-dev
      - libxkbcommon-dev
      - libpixman-1-dev
      - libpng-dev
      - libxcb1-dev
      - libxcb-composite0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-render0-dev
      - libxcb-xfixes0-dev
      - libxcb-xinput-dev
      - libpcre3-dev
      - libpam0g-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libwayland-egl-backend-dev
      - libwayland-dev
      - libwayland-egl1
    stage-packages:
      # - libdrm2  # INFO: comes from (x)wayland
      # - libegl1  # INFO: comes from (x)wayland
      - libevdev2
      # - libgbm1  # INFO: comes from (x)wayland
      # - libgles2 # INFO: comes from (x)wayland
      # - libglvnd0 # INFO: comes from (x)wayland
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libxcb-composite0
      - libxkbcommon0
      - libwinpr2-2
      - libxcb-icccm4
      - libxcb-xinput0

      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpng16-16
      - libthai0
      - libx11-xcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-xkb1 ## TODO: is needed ?
      - libxext6
      - libxkbfile1 ## TODO: is needed ?
      - libxrender1
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-bin ## TODO: only for test
    # stage-snaps:
    #   - wlroots/latest/edge
    stage:
      - -etc/sway/config
    # stage-snaps: 
    #   - dlmenu-wl
    #   # - wayland


  swayidle:
    after: [ sway ]
    source: https://github.com/swaywm/swayidle.git
    source-tag: '1.5'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dlogind=enabled


  swaybg:
    after: [ sway ]
    source: https://github.com/swaywm/swaybg.git
    source-tag: '1.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled


  swaylock:
    after: [ sway ]
    source: https://github.com/swaywm/swaylock.git
    source-tag: '1.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled
      - -Dpam=enabled


  dmenu-wayland:
    plugin: meson
    source: https://github.com/nyyManni/dmenu-wayland.git
    # source-tag:
    meson-parameters:
      - --prefix=/usr


  needed-tools:
    plugin: nil
    stage-packages:
      - i3status
      # - i3-wm    ## TODO: find a replacement for i3-config-wizard, and others
      - suckless-tools
      - xwayland
    stage:
      # - -etc/pam.d
      - -usr/share/doc
      - -usr/share/include
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      #- -usr/share/xsessions
      # - etc
      # - usr/bin
      # - usr/lib

