name: sway
# title:
type: app
base: core18
version: '1.2.0-77-0dev2'
summary: i3-compatible Wayland compositor
description: |
  Sway is a tiling window manager and Wayland compositor, inspired by i3, and written in C. It is designed as a drop in replacement for i3 using the more modern Wayland display server protocol and wlroots compositor library.
# license:

# icon: sway.png

# adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: strict

environment:
  SHELL: bash
  # LANG: null
  LC_ALL: C
  # LC_ALL: C.UTF-8

  # --- Snap compatibality ---
  SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET} # FIXME: how to get this, on runtime ? e. g. gcc -dumpmachine

  LD_LIBRARY_PATH: ${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${LD_LIBRARY_PATH}
  PATH: $SNAP/bin:$SNAP/usr/bin:${PATH}

  SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
  SNAPCRAFT_PRELOAD: ${SNAP}
  LD_PRELOAD: ${SNAP}/lib/libsnapcraft-preload.so #:${SNAP}/lib/bindtextdomain.so # TODO: also in gnome
  # LD_PRELOAD: ${SNAP}/lib/libsnapcraft-preload.so

  # -- Xkb-Library ---
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb # :${XKB_CONFIG_ROOT} # TODO: also in gnome
  # XKB_LOG_LEVEL: 50
  # XKB_LOG_VERBOSITY: 10

  # --- XDG config ---
  XDG_SESSION_TYPE: wayland
  XDG_CACHE_HOME:  ${SNAP_USER_COMMON}/.cache
  # XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: ${SNAP_USER_DATA}/.config

  # --- locale ---
  LOCPATH: ${SNAP}/usr/lib/locale:${LOCPATH} # TODO: also in gnome
  XLOCALEDIR: ${SNAP}/usr/share/X11/locale:${XLOCALEDIR} # TODO: also in gnome

  # --- Fonts ---
  FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf:${FONTCONFIG_FILE} # TODO: also in gnome
  FONTCONFIG_PATH: ${SNAP}/etc/fonts:${FONTCONFIG_PATH} # TODO: also in gnome

  # --- X ---
  XCURSOR_PATH: ${SNAP}/data-dir/icons:${SNAP}/usr/share/icons:${XCURSOR_PATH}  # TODO: also in gnome  # TODO: data-dir ?

  # --- Prep EGL ---
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d:${__EGL_VENDOR_LIBRARY_DIRS}
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:${LIBGL_DRIVERS_PATH} ## TODO: also in gnome
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:${LIBVA_DRIVERS_PATH}
  # TODO: FIXME: special case for nvidia: https://github.com/plars/stellarium-snap/pull/2/files

  # --- Prep GDK, GTK, Clutter ---
  GDK_BACKEND: wayland
  CLUTTER_BACKEND: wayland

  # GDK_PIXBUF_BINARY_VERSION: '2.10.0' # FIXME: how to get this from installed version ?
  GDK_PIXBUF_MODULEDIR: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders:${GDK_PIXBUF_MODULEDIR}  # TODO: also in gnome
  # # with: gdk-pixbuf-query-loaders > $libdir/gdk-pixbuf-2.0/$binary_version/loaders.cache
  # GDK_PIXBUF_MODULE_FILE: ${SNAP_USER_COMMON}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders.cache

  GTK_PATH: ${SNAP}/usr/lib/$ARCH/gtk-3.0:${GTK_PATH}:${GTK_PATH} # TODO: also in gnome

  # --- Gobject introspection ---
  GI_TYPELIB_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/girepository-1.0:${GI_TYPELIB_PATH} # TODO: also in gnome

  # --- GIO ---
  GIO_MODULE_DIR: ${SNAP_USER_COMMON}/.cache/gio-modules:${GIO_MODULE_DIR}

  # --- GTK ImLib ---
  GTK_IM_MODULE_DIR:  ${SNAP_USER_COMMON}/.cache/immodules  # FIXME: ${XDG_CACHE_HOME}/immodules
  GTK_IM_MODULE_FILE: ${SNAP_USER_COMMON}/.cache/immodules/immodules.cache



apps:
  sway:
    #command: LD_PRELOAD=${SNAP}/lib/libsnapcraft-preload.so sway -V -d
    #command: bin/snapcraft-preload $SNAP/usr/bin/sway -V -d
    command: usr/bin/sway
    #command: glue/startsway
    extensions:
      - gnome-3-28
    desktop: usr/share/wayland-sessions/sway.desktop
  swaybar:
    command: usr/bin/swaybar
    aliases: [ swaybar ]
  swaybg:
    command: usr/bin/swaybg
    aliases: [ swaybg ]
  swayidle:
    command: usr/bin/swayidle
    aliases: [ swayidle ]
  swaylock:
    command: usr/bin/swaylock
    aliases: [ swaylock ]
  swaymsg:
    command: usr/bin/swaymsg
    aliases: [ swaymsg ]
  swaynag:
    command: usr/bin/swaynag
    aliases: [ swaynag ]


slots:
  x11-slot:
    interface: x11
  wayland-slot:
    interface: wayland


plugs:
  wayland:
  x11:
  desktop:
  desktop-legacy:
  opengl:
  framebuffer:
  hardware-observe:
  display-control:
  locale-control:
  login-session-control:
  login-session-observe:
  home:
  system-observe:
  mount-observe:


layout:
  # /etc/sway:
  #   symlink: $SNAP/etc/sway
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  # /usr/share/fonts:
  #   symlink: $SNAP/usr/share/fonts
  # $SNAP/usr/share/fonts:
  #   bind: /usr/share/fonts
  


build-packages:
  - cmake # meson likes cmake
  - ctags # meson
  - pkgconf
  - quilt


parts:
  snapcraft-preload:
    source: https://github.com/sd-hd/snapcraft-preload.git
    source-branch: lib_version
    # source: snapcraft-preload/
    # source-type: local
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    # stage-packages:
    # - lib32gcc1
    # - lib32stdc++6
    # - libc6-i386


  externals:
     plugin: dump
     source: .
     organize:
       sway-config: etc/sway/config


  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.18'
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin


  json-c:
    source: https://github.com/json-c/json-c.git
    # source-tag: json-c-0.13.1-20180305
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]


  sway:
    after: [ json-c, wayland-protocols ] ## TODO: optional after xwayland
    source: https://github.com/swaywm/sway.git
    source-tag: 'v1.2'
    plugin: meson
    meson-version: 0.52.0
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
      #- --buildtype=release
      -  -Dman-pages=disabled
      -  -Dgdk-pixbuf=enabled
      -  -Dtray=disabled ## TODO: needs libsystemd
      -  -Dxwayland=enabled

      - -Dfreerdp=disabled ## TODO: from wlroots
      - -Dwlroots:freerdp=disabled ## TODO: from wlroots

      - -Dlibcap=enabled
      - -Dlogind=enabled
      - -Dlogind-provider=systemd

      - -Dexamples=false

      - -Dwlroots:xdg_dir=true
    override-pull: |
      set -eux
      snapcraftctl pull      
      # git clone https://github.com/sd-hd/wlroots.git subprojects/wlroots
      # git clone -b 0.8.1 https://github.com/swaywm/wlroots.git subprojects/wlroots
      git clone -b sway-snap-dev https://github.com/sd-hd/wlroots.git subprojects/wlroots
      # mkdir -p subprojects
      # cd subprojects/wlroots
      # git checkout 6bb7639a
      # git checkout 2a63f4fc61185693c8917b28863eb9739096026f  # d113e48a2a32542fe6e12f1759f07888364609bf
    # build-snaps: ## TODO: 
    #   - wayland
    build-packages:
      - libcairo2-dev
      - libdbus-1-dev
      - libevdev-dev
      - libdrm-dev
      - libpango1.0-dev
      - libjson-c-dev
      - libgdk-pixbuf2.0-dev
      - libsystemd-dev
      - libcap-dev
      - libgbm-dev
      - libinput-dev
      - libxkbcommon-dev
      - libpixman-1-dev
      - libpng-dev
      - libxcb1-dev
      - libxcb-composite0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-render0-dev
      - libxcb-xfixes0-dev
      - libxcb-xinput-dev
      - libpcre3-dev
      - libpam0g-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libwayland-egl-backend-dev
      - libwayland-dev
      - libwayland-egl1
    stage-packages:
      - libdrm2
      - libegl1
      - libevdev2
      - libgbm1
      - libgles2
      - libglvnd0
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libxcb-composite0
      - libxkbcommon0
      - libwinpr2-2
      - libxcb-icccm4
      - libxcb-xinput0

      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpng16-16
      - libthai0
      - libx11-xcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-xkb1 ## TODO: is needed ?
      - libxext6
      - libxkbfile1 ## TODO: is needed ?
      - libxrender1
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-bin ## TODO: only for test
    stage:
      - -etc/sway/config
    # stage-snaps: 
    #   - dlmenu-wl
    #   # - wayland


  swayidle:
    after: [ sway ]
    source: https://github.com/swaywm/swayidle.git
    source-tag: '1.5'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dlogind=enabled


  swaybg:
    after: [ sway ]
    source: https://github.com/swaywm/swaybg.git
    source-tag: '1.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled


  swaylock:
    after: [ sway ]
    source: https://github.com/swaywm/swaylock.git
    source-tag: '1.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled
      - -Dpam=enabled


  dmenu-wayland:
    plugin: meson
    source: https://github.com/nyyManni/dmenu-wayland.git
    # source-tag:
    meson-parameters:
      - --prefix=/usr


  needed-tools:
    plugin: nil
    stage-packages:
      - i3status
      # - i3-wm    ## TODO: find a replacement for i3-config-wizard, and others
      - suckless-tools
    stage:
      # - -etc/pam.d 
      - -usr/share/doc
      - -usr/share/include
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      #- -usr/share/xsessions

      # - etc
      # - usr/bin
      # - usr/lib

  debug:
    plugin: nil
    stage-packages: 
      - ltrace


  test-apps:
    plugin: nil
    stage-packages:
    # - lxterminal
    # - x11-apps
      - sakura
      - lilyterm
    stage-snaps:
      - termite/latest/candidate
    stage:
      - -usr/share/doc
      - -usr/share/include
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -usr/share/X11/xkb


  xwayland:
    plugin: nil
    stage-snaps:
      - wayland/latest/beta
    stage:
      - -usr/share/include
      - -usr/share/pkgconfig
      - -usr/share/wayland-protocols ## TODO: fix pkgconfig paths here
      - -usr/share/X11/xkb
    # prime:
    #   - etc
    #   # - lib # FIXME: 
    #   - usr/bin
      
    #   - usr/lib
    #   - usr/share/locale # FIXME:
    #   - usr/share/libdrm # TODO: move to other place
    #   - usr/share/X11 # FIXME:

    #   ## TODO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    #   - -usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
      

