name: sway
# title:
type: app
base: core18
version: '1.0'
summary: i3-compatible Wayland compositor
description: |
  Sway is a tiling window manager and Wayland compositor, inspired by i3, and written in C. It is designed as a drop in replacement for i3 using the more modern Wayland display server protocol and wlroots compositor library.
# license:

# icon: sway.png

# adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

# architectures:
#   - build-on: [amd64, i386]
#     run-on: [amd64, i386]


apps:
  sway:
    command: usr/bin/sway
  swaybar:
    command: usr/bin/swaybar
    aliases: [ swaybar ]
  swaymsg:
    command: usr/bin/swaymsg
    aliases: [ swaymsg ]
  swaynag:
    command: usr/bin/swaynag
    aliases: [ swaynag ]


build-packages:
  - cmake # meson likes cmake
  - pkgconf
  - quilt


parts:
  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.17'
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin


  json-c:
    source: https://github.com/json-c/json-c.git
    # source-tag: json-c-0.13.1-20180305
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]


  wlroots:
    after: [ wayland-protocols ]
    source: https://github.com/swaywm/wlroots.git
    source-tag: '0.5.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages: ## TODO: find out the needed dependencies !
      - libgtk-3-dev
      - gtk-doc-tools
      - gnutls-bin
      - valac
      - intltool
      - libgbm-dev
      - libpcre2-dev
      - libglib3.0-cil-dev
      - libgnutls28-dev
      - libgirepository1.0-dev
      - libxml2-utils
      - gperf
      # - libweston-5-dev
      - libfontconfig1-dev
      - freerdp2-dev
      - libfreetype6-dev
      # - libinput-dev
      - libxrender-dev
      - libx11-dev
      - libxext-dev
      - libpng-dev
      - libsm-dev
      - xutils-dev
      - libxt-dev
      - libpixman-1-dev
      - libwinpr2-dev
      - libxcb1-dev
      - libxcb-icccm4-dev
      - libxcb-xinput-dev
      - libxcb-render0-dev
      - libxcb-shm0-dev
      - zlib1g-dev
      - liblzo2-dev
    stage-packages:
      - libevdev2
      - libgles2
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libwayland-client0
      - libwayland-server0
      - libwayland-egl1
      - libxcb-composite0
      - libxcb-render0
      - libxkbcommon0
      - libwinpr2-2
      - libxcb-icccm4
      - libxcb-xinput0


  sway:
    after: [ json-c, wlroots ]
    source: https://github.com/swaywm/sway.git
    source-tag: '1.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd0
      - libsystemd-dev
      - ctags
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libcap2-bin ## TODO:
    stage-packages:
      - libcairo2
      - libdatrie1
      - libegl1
      - libevdev2
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgl1-mesa-dri
      - libgles2
      - libgraphite2-3
      - libgudev-1.0-0
      - libharfbuzz0b
      - libinput10
      - libmtdev1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre3
      - libpixman-1-0
      - libsystemd0
      - libthai0
      - libwacom2
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxcb-composite0
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxext6
      - libxkbcommon0
      - libxrender1

    override-build: |
      set -eux
      snapcraftctl build
      setcap "cap_sys_ptrace,cap_sys_tty_config=eip" $SNAPCRAFT_PART_INSTALL/usr/bin/sway
    install: |
      set -eux
      snapcraftctl build
      setcap "cap_sys_ptrace,cap_sys_tty_config=eip" $SNAP/usr/bin/sway

