name: sway
base: core18
version: '1.2.6'
summary: i3-compatible Wayland compositor
description: |
  Sway is a tiling window manager and Wayland compositor, inspired by i3, and written in C. It is designed as a drop in replacement for i3 using the more modern Wayland display server protocol and wlroots compositor library.

# icon: sway.png

# architectures:
#   - build-on: [amd64, i386]
#     run-on: [amd64, i386]

#adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots


environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
  PATH: $SNAP/bin:$SNAP/usr/bin:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri


apps:
  sway:
    command: usr/bin/sway
    # adapter: full
    desktop: usr/share/wayland-sessions/sway.desktop
    # plugs:
    #   - desktop
    #   - desktop-legacy
    #   - wayland
    #   - opengl
    # #   # - gsettings
    #   - network
    #   - x11
    #  - hardware-observe
    #  - locale-control
    #  - network-observe
    #  - system-observe
    #  - home
  swaybar:
    command: usr/bin/swaybar
    #    plugs:
    #      - desktop
    #      - wayland
  swaybg:
    command: usr/bin/swaybg
    #   plugs:
    #     - desktop
    #     - wayland
  swayidle:
    command: usr/bin/swayidle
  swaylock:
    command: usr/bin/swaylock
  swaymsg:
    command: usr/bin/swaymsg
    # plugs:
    #   - desktop
    #   - wayland
  swaynag:
    command: usr/bin/swaynag

# slots:
#   wayland:

# plugs: ## FIXME: remove unneeded
#   wayland:
#   opengl:
#   x11:
#   hardware-observe:
#   locale-control:
#   network-observe:
#   system-observe:
#   home:


parts:
  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.18'
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin

  json-c:
    source: https://github.com/json-c/json-c.git
    # source-tag: json-c-0.13.1-20180305
    plugin: autotools
    configflags: [ --prefix=/usr ]

  wlroots:
    after: [wayland-protocols]
    source: https://github.com/swaywm/wlroots.git
    source-tag: '0.8.1'
    plugin: meson
    meson-version: 0.51.2
    meson-parameters:
      - --prefix=/usr
      - -Dfreerdp=disabled
      - -Dlibcap=enabled
      - -Dlogind=enabled
      - -Dlogind-provider=systemd
      - -Dexamples=false
    build-packages:
      - libwayland-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libgbm-dev
      - libinput-dev
      - libxkbcommon-dev
      - libpixman-1-dev
      - libpng-dev
      - libsystemd-dev
      - libcap-dev
    stage-packages:
      - libdrm2
      - libegl1
      - libevdev2
      - libgbm1
      - libgles2
      - libglvnd0
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libwayland-client0
      - libwayland-egl1
      - libwayland-server0
      - libxkbcommon0
    stage: [usr]

  sway:
    after: [wlroots, json-c]
    source: https://github.com/swaywm/sway.git
    source-tag: '1.2'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libcairo2-dev
      - libpango1.0-dev
      - libgdk-pixbuf2.0-dev
    stage-packages:
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpng16-16
      - libthai0
      - libxcb-render0
      - libxcb-shm0
      - libxrender1

  swayidle:
    after: [ wlroots, sway ]
    source: https://github.com/swaywm/swayidle.git
    source-tag: '1.5'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      - libwayland-dev
      - libsystemd-dev
      # - meson
      # - scdoc


  swaybg:
    after: [ wlroots,sway ]
    source: https://github.com/swaywm/swaybg.git
    source-tag: '1.0'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      # - meson
      - libsystemd-dev
      - libwayland-dev
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      # - scdoc
    stage-packages:
      - libcairo2
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libpng16-16
      - libxcb-render0
      - libxcb-shm0
      - libxrender1



  swaylock:
    after: [ wlroots,sway ]
    source: https://github.com/swaywm/swaylock.git
    source-tag: '1.4'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      - libwayland-dev
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      - libpam0g-dev
      - libxkbcommon-dev
      # - meson
      # - scdoc
    stage-packages:
      - libcairo2
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libpng16-16
      - libxcb-render0
      - libxcb-shm0
      - libxrender1

  # mesa:
  #   plugin: nil
  #   stage-packages:
  #     - libgl1-mesa-dri
  #     - libwayland-egl1-mesa
  #     - libglu1-mesa


  # wayland:
  #   plugin: nil
  #   stage-packages:
  #     - libwayland-client0
  #     - libwayland-cursor0
  #     - libwayland-server0
