name: sway
# title:
type: app
base: core18
version: '1.2.0-7'
summary: i3-compatible Wayland compositor
description: |
  Sway is a tiling window manager and Wayland compositor, inspired by i3, and written in C. It is designed as a drop in replacement for i3 using the more modern Wayland display server protocol and wlroots compositor library.
# license:

# icon: sway.png

# adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

# architectures:
#   - build-on: [amd64, i386]
#     run-on: [amd64, i386]


environment:
  SHELL: bash
  #
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}
  PATH: $SNAP/bin:$SNAP/usr/bin:${PATH}

  # --- Snap compatibality ---
  SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET} # FIXME: how to get this, on runtime ? e. g. gcc -dumpmachine

  # -- Xkb-Library ---
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
  # XKB_LOG_LEVEL: 50
  # XKB_LOG_VERBOSITY: 10

  # --- XDG config ---
  XDG_CACHE_HOME:  ${SNAP_USER_COMMON}/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg # :$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: ${SNAP_USER_DATA}/.config

  # --- Prep EGL ---
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

  # --- Prep GDK, GTK, Clutter ---
  GDK_PIXBUF_BINARY_VERSION: '2.10.0' # FIXME: how to get this from installed version ?
  GDK_BACKEND: wayland
  CLUTTER_BACKEND: wayland
  # FIXME: loaders.cache should be created after install/refresh
  GDK_PIXBUF_MODULEDIR: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders/
  # FIXME: generate loaders.cache file ?!
  # with: gdk-pixbuf-query-loaders > $libdir/gdk-pixbuf-2.0/$binary_version/loaders.cache
  # GDK_PIXBUF_MODULE_FILE: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders.cache
  GDK_PIXBUF_MODULE_FILE: ${SNAP_USER_COMMON}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders.cache

  GTK_PATH: ${SNAP}/usr/lib/$ARCH/gtk-3.0:${GTK_PATH}

  # --- Qt ---
  QT_DEBUG_PLUGINS: 1
  # QTVER: qt5
  QT_QPA_PLATFORM: wayland-egl
  QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
  #QT_PLUGIN_PATH: $QTDIR/lib/plugins/
  QT_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins # FIXME: is this needed ?

  QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml


apps:
  sway:
    command: usr/bin/sway
    desktop: usr/share/wayland-sessions/sway.desktop
  swaybar:
    command: usr/bin/swaybar
    aliases: [ swaybar ]
  swaybg:
    command: usr/bin/swaybg
    aliases: [ swaybg ]
  swayidle:
    command: usr/bin/swayidle
    aliases: [ swayidle ]
  swaylock:
    command: usr/bin/swaylock
    aliases: [ swaylock ]
  swaymsg:
    command: usr/bin/swaymsg
    aliases: [ swaymsg ]
  swaynag:
    command: usr/bin/swaynag
    aliases: [ swaynag ]

build-packages:
  - cmake # meson likes cmake
  - pkgconf
  - quilt


parts:
  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.18'
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin

  json-c:
    source: https://github.com/json-c/json-c.git
    # source-tag: json-c-0.13.1-20180305
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]

  wlroots:
    after: [ wayland-protocols ]
    source: https://github.com/swaywm/wlroots.git
    source-commit: '9796abccedef881e99d293a2658c4da9466acd88'
    # source-tag: '0.8.1'
    source-depth: 1
    plugin: meson
    meson-version: 0.52.0
    meson-parameters:
      - --prefix=/usr
      - -Dfreerdp=disabled
      - -Dlibcap=enabled
      - -Dlogind=enabled
      - -Dlogind-provider=systemd
      - -Dexamples=false
    build-packages:
      - libwayland-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libgbm-dev
      - libinput-dev
      - libxkbcommon-dev
      - libpixman-1-dev
      - libpng-dev
      - libsystemd-dev
      - libcap-dev
    stage-packages:
      - libdrm2
      - libegl1
      - libevdev2
      - libgbm1
      - libgles2
      - libglvnd0
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libxcb-composite0
      - libxcb-render0
      - libxkbcommon0
      - libwinpr2-2
      - libxcb-icccm4
      - libxcb-xinput0


  sway:
    after: [ json-c, wlroots ]
    source: https://github.com/swaywm/sway.git
    source-tag: '1.2'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      #- --buildtype=release
      -  -Dman-pages=disabled
      -  -Dgdk-pixbuf=enabled
      -  -Dtray=disabled ## TODO: needs libsystemd
      -  -Dxwayland=enabled

      - -Dlibcap=enabled
      - -Dlogind=enabled
      - -Dlogind-provider=systemd

      - -Dexamples=false
    build-packages:
      - libcairo2-dev
      - libpango1.0-dev
      - libgdk-pixbuf2.0-dev
      - libsystemd0
      - libsystemd-dev
      - libcap2-bin
    stage-packages:
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpng16-16
      - libthai0
      - libxcb-render0
      - libxcb-shm0
      - libxrender1

  swayidle:
    after: [ sway ]
    source: https://github.com/swaywm/swayidle.git
    source-tag: '1.5'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dlogind=enabled


  swaybg:
    after: [ sway ]
    source: https://github.com/swaywm/swaybg.git
    source-tag: '1.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled


  swaylock:
    after: [ sway ]
    source: https://github.com/swaywm/swaylock.git
    source-tag: '1.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman-pages=disabled
      - -Dgdk-pixbuf=enabled
      - -Dpam=enabled


  # mesa:
  #   plugin: nil
  #   stage-packages:
  #     - libegl-mesa0
  #     - libegl1-mesa
  #     - libgl1-mesa-dri
  #     - libwayland-egl1-mesa
  #     - libglu1-mesa
  #     - mesa-va-drivers
  #     - mesa-vdpau-drivers
  #     - mesa-vulkan-drivers
  #     - libglx-mesa0
  #     - libglw1-mesa


  egl: # TODO: check who needs what ...
    plugin: nil
    stage-packages:
      - libdrm2

      - libglvnd0
      - libegl1
      - libvdpau-va-gl1
      # 
      - libgl1
      - libgl2ps1.4
      - libglx0
      - libgle3
      - libgles1
      - libgles2
      # - libglew2.1

      - libglbinding2

      - libvdpau1
      - libva-drm2
      - vdpau-driver-all
      - va-driver-all
      - libxcb-dri2-0
      - libxcb-dri3-0

      #
      - libglfw3-wayland
      - libwayland-egl1
      # - libwayland-egl++0 ## TODO: not found on core18
      - on amd64,i386:
        - libdrm-intel1
      - try:
        - libdrm-amdgpu1
      - try:
        - libdrm-nouveau2
      - try:
        - libdrm-radeon1
      - try:
        - libnvidia-egl-wayland1


  wayland:
    plugin: nil
    stage-packages:
      - libwayland-egl1 # | libwayland-egl1-mesa
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-server0
