name: sway
base: core18
version: '1.2.6'
summary: SWAY Wayland tiling window manager desktop (experimental)
description: |
  SWAY is a i3-compatible Wayland compositor
  This snap is tested on ubuntu

# icon: sway.png

# architectures:
#   - build-on: [amd64, i386]
#     run-on: [amd64, i386]

#adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
  PATH: $SNAP/bin:$SNAP/usr/bin:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri


apps:
  sway:
    command: usr/bin/sway
    # adapter: full
    desktop: usr/share/wayland-sessions/sway.desktop
    # plugs:
    #   - desktop
    #   - desktop-legacy
    #   - wayland
    #   - opengl
    # #   # - gsettings
    #   - network
    #   - x11
    #  - hardware-observe
    #  - locale-control
    #  - network-observe
    #  - system-observe
    #  - home
  swaybar:
    command: usr/bin/swaybar
    #    plugs:
    #      - desktop
    #      - wayland
  swaybg:
    command: usr/bin/swaybg
    #   plugs:
    #     - desktop
    #     - wayland
  swayidle:
    command: usr/bin/swayidle
  swaylock:
    command: usr/bin/swaylock
  swaymsg:
    command: usr/bin/swaymsg
    # plugs:
    #   - desktop
    #   - wayland
  swaynag:
    command: usr/bin/swaynag

# slots:
#   wayland:

# plugs: ## FIXME: remove unneeded
#   wayland:
#   opengl:
#   x11:
#   hardware-observe:
#   locale-control:
#   network-observe:
#   system-observe:
#   home:


parts:
  wayland-protocols: # TODO: check weston version of disco release
    after: [ json-c ]
    source: https://github.com/wayland-project/wayland-protocols.git
    source-tag: '1.18'
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - pkgconf
      - cmake
      - gcc
      - g++
      - gtk-doc-tools
      - gnutls-bin 
      - valac
      - intltool
      - libpcre2-dev
      - libglib3.0-cil-dev 
      - libgnutls28-dev 
      - libgirepository1.0-dev
      - libxml2-utils
      - gperf
      - build-essential
      - gir1.2-colord-1.0
      - libcolord-dev 
      - libjpeg-dev
      - libjpeg-turbo8-dev
      - libjpeg8-dev
      - liblcms2-dev
      - libvpx-dev
      - quilt
      #
      - libwayland-dev
      - libinput-dev
      - libcap-dev
      # - wayland-protocols ## TODO: on 19.04 there is the correct version
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libdrm-dev
      - libgbm-dev
      - libxkbcommon-dev
      - libudev-dev
      - libpixman-1-dev
      - libxcb-composite0-dev
      - libxcb-xfixes0-dev
      - libxcb-image0-dev
      - libxcb-render0-dev
      - libx11-xcb-dev
  json-c:
    source: https://github.com/json-c/json-c.git
    # source-tag: json-c-0.13.1-20180305
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - cmake
      - clang
      - build-essential
      - doxygen
      - autoconf
      - automake-1.15
      - libtool
  wlroots:
    after: [ json-c,wayland-protocols ]
    source: https://github.com/swaywm/wlroots.git
    #source-tag: '0.8.1'
    source-commit: '9796abccedef881e99d293a2658c4da9466acd88'
    plugin: meson
    meson-version: 0.52.0
    meson-parameters: [ '--prefix=/usr', '-Dfreerdp=disabled' ]
    build-packages: ## TODO: find out the needed dependencies !
      - pkgconf
      - cmake
      - g++
      - libgtk-3-dev
      - gtk-doc-tools
      - gnutls-bin
      - valac
      - intltool
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libgbm-dev
      - libpcre2-dev
      - libglib3.0-cil-dev
      - libgnutls28-dev
      - libgirepository1.0-dev
      - libxml2-utils
      - gperf
      # - libweston-5-dev
      - libfontconfig1-dev
      - freerdp2-dev
      - libfreetype6-dev
      # - libinput-dev
      # - libpixman-1-dev
      - libxrender-dev
      - libx11-dev
      - libxext-dev
      - libpng-dev
      - libsm-dev
      - xutils-dev
      - libxt-dev
      - libpixman-1-dev
      - libwinpr2-dev
      - libxcb1-dev
      - libxcb-icccm4-dev
      - libxcb-xinput-dev
      - libxcb-render0-dev
      - libxcb-shm0-dev
      - zlib1g-dev
      - liblzo2-dev
    stage-packages:
      - libevdev2
      - libgles2
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libpixman-1-0
      - libwacom2
      - libwayland-client0
      - libwayland-server0
      - libwayland-egl1
      - libxcb-composite0
      - libxcb-render0
      - libxkbcommon0
      - libwinpr2-2
      - libxcb-icccm4
      - libxcb-xinput0
  sway:
    after: [ json-c,wlroots ] 
    # source: https://github.com/swaywm/sway.git
    # source-tag: '1.2'
    source: https://salsa.debian.org/swaywm-team/sway.git
    source-tag: 'debian/1.2-1'
    plugin: meson
    meson-version: 0.51.2
    meson-parameters: [ --prefix=/usr ]
    # override-pull: | ## FIXME: TODO: download wlroots submodule
    #   set -eux
    #   git pull --submodule --recurive
    build-packages:
      - libsystemd0
      - libsystemd-dev
      # - scdoc
      - ctags
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libcap2-bin ## TODO:
    stage-packages:
      # - libcairo2
      - libdatrie1
      - libegl1
      - libevdev2
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgl1-mesa-dri
      - libgles2
      - libgraphite2-3
      - libgudev-1.0-0
      - libharfbuzz0b
      - libinput10
      - libmtdev1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre3
      - libpixman-1-0
      - libsystemd0
      - libthai0
      - libwacom2
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxcb-composite0
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxext6
      - libxkbcommon0
      - libxrender1

    # override-build: |
    #   set -eux
    #  snapcraftctl build
    #   ln -s $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libcairo.so.2 $SNAP/usr/lib/libcairo.so.2
    #   setcap "cap_sys_ptrace,cap_sys_tty_config=eip" $SNAPCRAFT_PART_INSTALL/usr/bin/sway
    # install: |
    #   set -eux
    #   snapcraftctl install
    #   cp -nf $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libcairo.so* $SNAPCRAFT_PART_INSTALL/usr/lib/
    #   setcap "cap_sys_ptrace,cap_sys_tty_config=eip" $SNAP/usr/bin/sway


  swayidle:
    after: [ wlroots, sway ]
    source: https://github.com/swaywm/swayidle.git
    source-tag: '1.5'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      - libwayland-dev
      - libsystemd-dev
      - pkgconf
      # - meson
      # - scdoc


  swaybg:
    after: [ wlroots,sway ]
    source: https://github.com/swaywm/swaybg.git
    source-tag: '1.0'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      # - meson
      - libsystemd-dev
      - libwayland-dev
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      - pkgconf
      # - scdoc


  swaylock:
    after: [ wlroots,sway ]
    source: https://github.com/swaywm/swaylock.git
    source-tag: '1.4'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      - libwayland-dev
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      - libpam0g-dev
      - libxkbcommon-dev
      # - meson
      - pkgconf
      # - scdoc


  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa


  wayland:
    plugin: nil
    stage-packages:
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-server0
